# For more information: https://laravel.com/docs/sail
version: '3'
services:
    backend_service:
        image: 192.53.115.165:5000/wealthzen-backend:latest
        ports:
            - '0.0.0.0:${BACKEND_PORT:-8081}:80'
        env_file:
            - .env
        networks:
            - sail
        depends_on:
            - mysql
    frontend_service:
        image: 192.53.115.165:5000/wealthzen-frontend:latest
        ports:
            - '0.0.0.0:${APP_PORT:-80}:80'
    optimizer_service:
        image: 192.53.115.165:5000/wealthzen-optimizer-service:latest
        ports:
            - '0.0.0.0:${OPTIMIZER_PORT:-8000}:8000'
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - './wealthzen_mysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
