@URI = http://127.0.0.1
@PORT = 5555
@VERSION = HTTP/1.1


# Add Questions
POST {{URI}}:{{PORT}}/api/questions {{VERSION}}
Content-Type: application/json

{
    "type": "CHOICE_INPUT",
    "question": "How much investable wealth do you have?",
    "button": "Continue",
    "choices": [
        {
            "text": "I am ok to share that with you",
            "value": "A",
            "order": 1,
            "form_variables": {
                "input": true
            },
            "placeholder": "Tell Us",
            "description": "SGD"
        },
        {
            "text": "I can't reveal that ",
            "value": "B",
            "order": 2,
            "description": "Let us assume it is $100,000"
        }
    ],
    "phase": 1,
    "order": 3
}