@URI = http://3.140.207.244
@PORT = 5555
@VERSION = HTTP/1.1


# Add Questions
POST {{URI}}:{{PORT}}/api/questions {{VERSION}}
Content-Type: application/json

  {
    "type": "MULTIPLE_CHOICE",
    "question": "What kind of funds/ ETFs do you own?",
    "choices": [
      {
        "text": "Diversified  (e.g. S&P 500 ETF)",
        "value": "A",
        "order": 1,
        "_id": "62b92eddf80058a9e23679c9"
      },
      {
        "text": "Sector / Geo specific (e.g. Pure Tech, only China)",
        "value": "B",
        "order": 2,
        "_id": "62b92eddf80058a9e23679ca"
      },
      {
        "text": "Some other",
        "value": "C",
        "order": 3,
        "_id": "62b92eddf80058a9e23679cb"
      }
    ],
    "button": "Continue",
    "phase": 1,
    "order": 9
  }


# GET {{URI}}:{{PORT}}/api/questions {{VERSION}}